[package]
name = "content-builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
serde = "1"
serde_json = "1"
wasm-logger = "0.2.0"
log = "0.4.6"
stylist = "0.10"